export default {
  PRODUCT_CODE: 'PRODUCT_CODE',
  MODULE_NAME: 'MODULE_NAME',
  BUILD_NUM: 'BUILD_NUM',
  PORT: 'PORT',
  MSSQLDB_HOST: "MSSQLDB_HOST",
  MSSQLDB_DBNAME: "MSSQLDB_DBNAME",
  MSSQLDB_USER: "MSSQLDB_USER",
  MSSQLDB_PASSWORD: "MSSQLDB_PASSWORD"
}
